# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 18b4bb0870700cd2c7f0b899fd245ed49ce5cece1ab8ee0d0707a0600d1e6e4d3e89e73db71d40cbc96c8f1bbf243e918726eac22a519c640e8ca34e6a9f04e5

test:
  secret_key_base: 21f10b678e8308a3e141d4e6b65baf5ce5156c3da54ffb9c5f2b758e3ddedb9886a9c886dec1856053e0f3b0c8e67879b0b7cbcba1b2d1bd6527dab1e86f1782

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
